<a href="https://colab.research.google.com/github/Maheshkumarcseb/Machine_learning/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Creating a matrix using numpy

In [2]:
matrix_1 = np.array([[1,2],[4,5]])
print(matrix_1)

[[1 2]
 [4 5]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
matrix_2.shape


(3, 3)

creating matrix with random values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.46034147 0.83638706 0.947413  ]
 [0.08537781 0.59104215 0.53322582]
 [0.44287197 0.84454285 0.56112212]]


In [9]:
#creating matrix with random integers
random_integer_matrix = np.random.randint(100,size=(5,5))
print(random_integer_matrix)

[[ 1 86 82 10 10]
 [85 50 18 56 24]
 [97 54 60 90 76]
 [82 99  2 10 58]
 [82 26 15 69 94]]


matrix as all the values as 1

In [10]:
matrix3=np.ones((3,3))
print(matrix3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


matrix as all the values as 0


In [11]:
matrix4=np.zeros((3,3))
print(matrix4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
matrix4=np.zeros((3,3),dtype=int)
print(matrix4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Identity matrix

In [16]:
identity_matrix=np.eye(3, dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Transpose of a Matrix

In [17]:
# matrix with a random integer values
a=np.random.randint(100,size=(3,3))
print(a)

[[35 18 95]
 [62 93 63]
 [80 31 10]]


In [18]:
transpose_of_a=np.transpose(a)
print(transpose_of_a)
#

[[35 62 80]
 [18 93 31]
 [95 63 10]]
