<a href="https://colab.research.google.com/github/Maheshkumarcseb/Machine_learning/blob/main/matrix_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Addition of two matrix


In [2]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
print(c)

[[ 6  8]
 [10 12]]


In [3]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
b=np.array([[5,6,7],[7,8,5],[2,5,3]])
c=a+b
print(c)

[[ 6  8 10]
 [10 12 10]
 [ 8 12 11]]


In [4]:
c.shape

(3, 3)

In [7]:
# create two matrix with random values
matrix_1=np.random.randint(1,10,size=(3,3))
matrix_2=np.random.randint(1,10,size=(3,3))
print(matrix_1)


[[6 9 1]
 [9 3 9]
 [3 5 2]]


In [8]:
print(matrix_2)

[[2 5 2]
 [2 1 4]
 [2 3 7]]


In [10]:
sum1=np.add(matrix_1,matrix_2)
print(sum1)

[[ 8 14  3]
 [11  4 13]
 [ 5  8  9]]


Matrix Subtraction

In [11]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a-b
print(c)

[[-4 -4]
 [-4 -4]]


In [12]:
e=np.subtract(a,b)
print(e)

[[-4 -4]
 [-4 -4]]


In [14]:
#create two matrices with random values
matrix_1=np.random.randint(1,10,size=(3,3))
matrix_2=np.random.randint(1,10,size=(3,3))
print(matrix_1)


[[5 5 2]
 [2 7 8]
 [2 5 1]]


In [15]:
print(matrix_2)

[[7 9 5]
 [5 8 7]
 [2 8 1]]


In [16]:
diff=np.subtract(matrix_1,matrix_2)
print(diff)

[[-2 -4 -3]
 [-3 -1  1]
 [ 0 -3  0]]


Multiply a matrix by  a scaler

In [18]:
x=5
y=np.random.randint(10,size=(4,4))
print(y)

[[9 1 5 8]
 [9 7 0 8]
 [9 7 7 2]
 [7 4 5 8]]


In [19]:
product=np.multiply(x,y)
print(product)

[[45  5 25 40]
 [45 35  0 40]
 [45 35 35 10]
 [35 20 25 40]]


Multiplication of two matrix

In [20]:
#crate two matrices with random values
matrix_1=np.random.randint(1,10,size=(3,3))
matrix_2=np.random.randint(1,10,size=(3,4))
print(matrix_1)

[[1 7 4]
 [4 6 1]
 [8 8 3]]


In [21]:
print(matrix_2)

[[5 7 1 5]
 [5 7 3 7]
 [9 1 7 3]]


In [22]:
mul=np.dot(matrix_1,matrix_2)
print(mul)

[[ 76  60  50  66]
 [ 59  71  29  65]
 [107 115  53 105]]


In [23]:
mul.shape

(3, 4)

Element wise matrix multiplication

In [24]:
#crate two matrices with random values
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,3))
print(matrix_1)

[[1 7 4]
 [4 6 1]
 [8 8 3]]


In [25]:
print(matrix_2)

[[5 7 1 5]
 [5 7 3 7]
 [9 1 7 3]]


In [26]:
prod=np.multiply(matrix_3,matrix_4)
print(prod)


[[ 2  3  0]
 [ 0  2  4]
 [ 3  0 16]]
